### ISSUE TITLE
pickle_dataset.py 

### ISSUE THREAD

**Issue by sarmadm** [mahakal/FacialEmotionRecognition#1]
HI

pickle_dataset.py is not saving pickle file , what should I do ?

**Comment by mahakal** [comment]
Do you have the cohn kanade dataset ???
Want seems to be the problem.

Have you checked 
https://github.com/mahakal/FacialEmotionRecognition#usage
https://github.com/mahakal/FacialEmotionRecognition/blob/master/pickle_dataset.py#L123

**Comment by sarmadm** [comment]
HI

Thanks for replying . 

Yes I have the extended CK data which is arranged as several folders and inside each folder there is

types of emotions as some of them has labels and others not. 


![capture](https://user-images.githubusercontent.com/14107864/47876089-45ff4380-de10-11e8-9a46-0cb0c96ece1f.JPG)


How should I make the pickle_dataset.py  to read through these folders and then use cnn.py ?

**Comment by mahakal** [comment]
https://github.com/mahakal/FacialEmotionRecognition/blob/master/pickle_dataset.py#L119  => put the absolute path of CK dataset.

open python terminal in the repo

```
from pickle_dataset import PickleData
p = PickleData()
p.start_pickling()
```

I might refactor the code so it takes care of the directory path, threshold, error handling, etc. But then again it's just pickling the data.

**Comment by sarmadm** [comment]
Hi

Images bath is : `C:/Users/sarmad/Documents/CK/cohn-kanade-images/`

where all folders are . I put this path in pickle_dataset.py and run the code in python terminal.

there is a file saved as .p but when I run cnn.py ,

`Using TensorFlow backend.
Traceback (most recent call last):
  File "cnn.py", line 34, in <module>
    X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1)
ValueError: cannot reshape array of size 0 into shape (8,100,100,1)`

**Comment by mahakal** [comment]
https://github.com/mahakal/FacialEmotionRecognition/blob/master/cnn.py#L25

Replace the name with the generated file.
I'm gonna rewrite it.

**Comment by sarmadm** [comment]
I renamed and replaced the file name but I get errors I showed in last message . I  think there is some problems with reading images from the folders

**Comment by sarmadm** [comment]
When I load and print pickle file this is the output :
`((array([], shape=(8, 0), dtype=float64), array([], shape=(0, 1), dtype=int8)), (array([], shape=(8, 0), dtype=float64), array([], shape=(0, 1), dtype=int8)), (array([], shape=(8, 0), dtype=float64), array([], shape=(0, 1), dtype=int8)))`

**Comment by mahakal** [comment]
@sarmadm Yeah, I'm rewriting the script making it more user-friendly. I'll be done by tomorrow.

**Comment by sarmadm** [comment]
Thanks , I tried running pickle.py is shows this error 

`pickle_dataset.py: error: the following arguments are required: C:/Users/Documents/CK/cohn-kanade-images`

This the folder that contains all the folders with images as shown in above image , how should I wrtire the path ?

**Comment by sarmadm** [comment]
Hi

I run the code again shows this error : 

`    X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1)
ValueError: cannot reshape array of size 0 into shape (8,100,100,1)`

is that the case with you ?

**Comment by mahakal** [comment]
There were some typos, try it again.

For Help:
python pickle_dataset.py -h
python cnn.py -h

Let me know whether it works or not. 
And can you tell me, for which purpose are you using the repository.

**Comment by sarmadm** [comment]
It shows same error , is it problem with ck data folder structure ?

`(keras_v) C:\Users\Documents\CK>python cnn.py C:\Users\Documents\CK\ck_dataset.pickle
Using TensorFlow backend.
Traceback (most recent call last):
  File "cnn.py", line 55, in <module>
    X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1)
ValueError: cannot reshape array of size 0 into shape (8,100,100,1)`

**Comment by mahakal** [comment]
The pickle file seems to be empty. Delete the previous pickle.py file.
Run, python pickle_dataset.py C:/Users/Documents/CK/cohn-kanade-images --crop
The pickle would be created in repo directory.
Then run, python cnn.py ck_dataset.pickle

Let me know whether it works or not.
**And can you tell me, for which purpose are you using the repository.**

**Comment by sarmadm** [comment]
I deteted the previous pickle file , and run : 

`(keras_v) C:\Users\Documents\CK>python pickle_dataset.py  C:\Users\Documents\CK\cohn-kanade-images`

> C:\Users\Documents\CK\cohn-kanade-images folder contains imaged sequence folders 

pickle file is saved and then I run : 

`(keras_v) C:\Users\Documents\CK>python cnn.py  C:\Users\Documents\CK\ck_dataset.pickle
Using TensorFlow backend.
Traceback (most recent call last):
  File "cnn.py", line 55, in <module>
    X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1)
ValueError: cannot reshape array of size 0 into shape (8,100,100,1)`

**Comment by sarmadm** [comment]
Any idea ??

**Comment by mahakal** [comment]
There was a bug in the code, fetch the latest and check.
And also, to check the pickle file you could

```
import pickle
o = pickle.load(open('name_of_the_file.pickle' 'rb'))
o.keys()
print(o)
```

**Comment by sarmadm** [comment]
It shows same error and this is ck_dataset.pickle output  : 

`dict_keys(['training_data', 'validation_data', 'test_data', 'img_dim'])
 print(o)`

  `{training_data': [array([], shape=(8, 0), dtype=float64), array([], shape=(0, 1), dtype=int8)], 
  'validation_data': [array([], shape=(8, 0), dtype=float64), array([], shape=(0, 1), dtype=int8)], 'test_data': 
  [array([], shape=(8, 0), dtype=float64), array([], shape=(0, 1), dtype=int8)], 'img_dim': {'width': 100, 
  'height': 100}}`

**Comment by mahakal** [comment]
Are you using CK database or Extended CK database???
Try again, there was a bug now the script works for CK database.

**Comment by sarmadm** [comment]
I'm using Extended CK database , is the code will not work for it ?
